from Demo_gym.envs.toy_text.blackjack import BlackjackEnv
from Demo_gym.envs.toy_text.roulette import RouletteEnv
from Demo_gym.envs.toy_text.frozen_lake import FrozenLakeEnv
from Demo_gym.envs.toy_text.nchain import NChainEnv
from Demo_gym.envs.toy_text.hotter_colder import HotterColder
from Demo_gym.envs.toy_text.guessing_game import GuessingGame
from Demo_gym.envs.toy_text.kellycoinflip import KellyCoinflipEnv
from Demo_gym.envs.toy_text.kellycoinflip import KellyCoinflipGeneralizedEnv
from Demo_gym.envs.toy_text.cliffwalking import CliffWalkingEnv
from Demo_gym.envs.toy_text.taxi import TaxiEnv
from Demo_gym.envs.toy_text.guessing_game import GuessingGame
from Demo_gym.envs.toy_text.hotter_colder import HotterColder
